apiVersion: v1
kind: ConfigMap
metadata:
  name: pending-pg
  namespace: sw
data:
  minAvailable: "3"
  scheduleTimeoutSeconds: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-example
  namespace: sw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        pod-group.scheduling.bdap.com/podgroup-configmap: pending-pg
    spec:
      schedulerName: gang-scheduler
      containers:
      - image: busybox
        name: busybox
        command: ["sleep", "infinity"]
