apiVersion: apps/v1
kind: Deployment
metadata:
  name: regpod-example
  namespace: sw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      schedulerName: gang-scheduler
      containers:
        - image: busybox
          name: busybox
          command: ["sleep", "infinity"]
